/**
 * Curated MCU sample data.
 *
 * Entities reference each other by a stable `key` (a slug), never by ObjectId -
 * the loader resolves keys to ids in a second pass. That keeps this file
 * hand-editable and makes re-running the seed idempotent.
 */

export const movies = [
  {
    key: "iron-man",
    title: "Iron Man",
    releaseYear: 2008,
    phase: "Phase 1",
    director: "Jon Favreau",
    runtime: 126,
    rating: 7.9,
    boxOffice: 585796247,
    synopsis:
      "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
  },
  {
    key: "the-avengers",
    title: "The Avengers",
    releaseYear: 2012,
    phase: "Phase 1",
    director: "Joss Whedon",
    runtime: 143,
    rating: 8.0,
    boxOffice: 1518815515,
    synopsis:
      "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.",
  },
  {
    key: "captain-america-the-winter-soldier",
    title: "Captain America: The Winter Soldier",
    releaseYear: 2014,
    phase: "Phase 2",
    director: "Anthony and Joe Russo",
    runtime: 136,
    rating: 7.7,
    boxOffice: 714421503,
    synopsis:
      "Steve Rogers struggles to embrace his role in the modern world and battles a new threat from old history: the Winter Soldier.",
  },
  {
    key: "guardians-of-the-galaxy",
    title: "Guardians of the Galaxy",
    releaseYear: 2014,
    phase: "Phase 2",
    director: "James Gunn",
    runtime: 121,
    rating: 8.0,
    boxOffice: 772776600,
    synopsis:
      "A group of intergalactic criminals must pull together to stop a fanatical warrior from taking control of the universe.",
  },
  {
    key: "doctor-strange",
    title: "Doctor Strange",
    releaseYear: 2016,
    phase: "Phase 3",
    director: "Scott Derrickson",
    runtime: 115,
    rating: 7.5,
    boxOffice: 677718395,
    synopsis:
      "A neurosurgeon discovers the hidden world of magic and alternate dimensions after a career-ending car accident.",
  },
  {
    key: "thor-ragnarok",
    title: "Thor: Ragnarok",
    releaseYear: 2017,
    phase: "Phase 3",
    director: "Taika Waititi",
    runtime: 130,
    rating: 7.9,
    boxOffice: 854229371,
    synopsis:
      "Imprisoned on Sakaar, Thor must race against time to return to Asgard and stop Hela and the destruction of his world.",
  },
  {
    key: "black-panther",
    title: "Black Panther",
    releaseYear: 2018,
    phase: "Phase 3",
    director: "Ryan Coogler",
    runtime: 134,
    rating: 7.3,
    boxOffice: 1347280838,
    synopsis:
      "T'Challa returns home to Wakanda to take his place as king, but a powerful enemy reappears to challenge the throne.",
  },
  {
    key: "avengers-infinity-war",
    title: "Avengers: Infinity War",
    releaseYear: 2018,
    phase: "Phase 3",
    director: "Anthony and Joe Russo",
    runtime: 149,
    rating: 8.4,
    boxOffice: 2048359754,
    synopsis:
      "The Avengers must stop Thanos from collecting all six Infinity Stones and wiping out half of all life.",
  },
  {
    key: "avengers-endgame",
    title: "Avengers: Endgame",
    releaseYear: 2019,
    phase: "Phase 3",
    director: "Anthony and Joe Russo",
    runtime: 181,
    rating: 8.4,
    boxOffice: 2799439100,
    synopsis:
      "After the devastating events of Infinity War, the remaining Avengers take one final stand to undo Thanos' snap.",
  },
];

export const characters = [
  {
    key: "tony-stark",
    name: "Tony Stark",
    alias: "Iron Man",
    description:
      "Genius, billionaire, playboy, philanthropist. Founder of Stark Industries and a founding member of the Avengers.",
    powers: ["Powered Armor", "Genius Intellect", "Flight", "Repulsor Blasts"],
    stats: { strength: 60, intelligence: 100, speed: 60, durability: 75, energy: 85, combat: 70 },
    theme: { colorPrimary: "#c8102e", colorSecondary: "#f0a500" },
    appearances: ["iron-man", "the-avengers", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["steve-rogers", "bruce-banner", "peter-parker", "stephen-strange"],
    artifactsUsed: ["arc-reactor", "infinity-gauntlet"],
  },
  {
    key: "steve-rogers",
    name: "Steve Rogers",
    alias: "Captain America",
    description:
      "The first Avenger. A World War II super soldier who became the moral center of Earth's mightiest heroes.",
    powers: ["Super Soldier Serum", "Peak Human Strength", "Shield Mastery", "Tactical Genius"],
    stats: { strength: 75, intelligence: 70, speed: 65, durability: 80, energy: 40, combat: 100 },
    theme: { colorPrimary: "#0a3161", colorSecondary: "#c8102e" },
    appearances: [
      "the-avengers",
      "captain-america-the-winter-soldier",
      "avengers-infinity-war",
      "avengers-endgame",
    ],
    affiliations: ["tony-stark", "natasha-romanoff", "bucky-barnes", "sam-wilson"],
    artifactsUsed: ["vibranium-shield", "mjolnir"],
  },
  {
    key: "thor-odinson",
    name: "Thor Odinson",
    alias: "Thor",
    description:
      "The God of Thunder and rightful king of Asgard. Wielder of Mjolnir and later Stormbreaker.",
    powers: ["Godly Strength", "Weather Manipulation", "Flight", "Longevity"],
    stats: { strength: 100, intelligence: 65, speed: 85, durability: 95, energy: 95, combat: 85 },
    theme: { colorPrimary: "#1e3a8a", colorSecondary: "#dc2626" },
    appearances: ["the-avengers", "thor-ragnarok", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["loki-laufeyson", "bruce-banner", "tony-stark"],
    artifactsUsed: ["mjolnir", "stormbreaker"],
  },
  {
    key: "bruce-banner",
    name: "Bruce Banner",
    alias: "Hulk",
    description:
      "A brilliant physicist whose exposure to gamma radiation transforms him into an unstoppable green giant.",
    powers: ["Superhuman Strength", "Regeneration", "Genius Intellect", "Limitless Rage"],
    stats: { strength: 100, intelligence: 95, speed: 60, durability: 100, energy: 50, combat: 65 },
    theme: { colorPrimary: "#15803d", colorSecondary: "#581c87" },
    appearances: ["the-avengers", "thor-ragnarok", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["tony-stark", "thor-odinson", "natasha-romanoff"],
    artifactsUsed: [],
  },
  {
    key: "natasha-romanoff",
    name: "Natasha Romanoff",
    alias: "Black Widow",
    description:
      "A former KGB assassin turned S.H.I.E.L.D. agent and founding Avenger, deadly without any powers.",
    powers: ["Master Assassin", "Espionage", "Acrobatics", "Multilingual"],
    stats: { strength: 45, intelligence: 80, speed: 65, durability: 50, energy: 20, combat: 95 },
    theme: { colorPrimary: "#7f1d1d", colorSecondary: "#111827" },
    appearances: [
      "the-avengers",
      "captain-america-the-winter-soldier",
      "avengers-infinity-war",
      "avengers-endgame",
    ],
    affiliations: ["steve-rogers", "bruce-banner", "clint-barton"],
    artifactsUsed: [],
  },
  {
    key: "clint-barton",
    name: "Clint Barton",
    alias: "Hawkeye",
    description: "A master marksman and S.H.I.E.L.D. agent who never misses his target.",
    powers: ["Master Archer", "Marksmanship", "Hand-to-Hand Combat"],
    stats: { strength: 45, intelligence: 70, speed: 55, durability: 50, energy: 20, combat: 90 },
    theme: { colorPrimary: "#4c1d95", colorSecondary: "#111827" },
    appearances: ["the-avengers", "avengers-endgame"],
    affiliations: ["natasha-romanoff", "steve-rogers"],
    artifactsUsed: [],
  },
  {
    key: "bucky-barnes",
    name: "Bucky Barnes",
    alias: "Winter Soldier",
    description:
      "Steve Rogers' closest friend, brainwashed into a HYDRA assassin before reclaiming his identity.",
    powers: ["Enhanced Strength", "Bionic Arm", "Master Marksman", "Espionage"],
    stats: { strength: 70, intelligence: 65, speed: 65, durability: 75, energy: 25, combat: 92 },
    theme: { colorPrimary: "#374151", colorSecondary: "#7f1d1d" },
    appearances: ["captain-america-the-winter-soldier", "avengers-infinity-war"],
    affiliations: ["steve-rogers", "sam-wilson"],
    artifactsUsed: [],
  },
  {
    key: "sam-wilson",
    name: "Sam Wilson",
    alias: "Falcon",
    description:
      "A former pararescue airman who fights alongside Captain America with a winged flight suit.",
    powers: ["Flight", "Aerial Combat", "Military Training"],
    stats: { strength: 45, intelligence: 65, speed: 70, durability: 50, energy: 30, combat: 80 },
    theme: { colorPrimary: "#b91c1c", colorSecondary: "#f3f4f6" },
    appearances: ["captain-america-the-winter-soldier", "avengers-infinity-war"],
    affiliations: ["steve-rogers", "bucky-barnes"],
    artifactsUsed: [],
  },
  {
    key: "peter-parker",
    name: "Peter Parker",
    alias: "Spider-Man",
    description:
      "A teenage genius from Queens with the proportionate abilities of a spider, mentored by Tony Stark.",
    powers: ["Wall-Crawling", "Spider-Sense", "Superhuman Agility", "Genius Intellect"],
    stats: { strength: 75, intelligence: 90, speed: 80, durability: 70, energy: 30, combat: 80 },
    theme: { colorPrimary: "#dc2626", colorSecondary: "#1d4ed8" },
    appearances: ["avengers-infinity-war", "avengers-endgame"],
    affiliations: ["tony-stark", "stephen-strange"],
    artifactsUsed: [],
  },
  {
    key: "stephen-strange",
    name: "Stephen Strange",
    alias: "Doctor Strange",
    description:
      "A former neurosurgeon who became Master of the Mystic Arts and guardian of the Time Stone.",
    powers: ["Sorcery", "Astral Projection", "Time Manipulation", "Portal Creation"],
    stats: { strength: 45, intelligence: 95, speed: 60, durability: 60, energy: 100, combat: 75 },
    theme: { colorPrimary: "#b45309", colorSecondary: "#7f1d1d" },
    appearances: ["doctor-strange", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["tony-stark", "peter-parker"],
    artifactsUsed: ["eye-of-agamotto", "cloak-of-levitation"],
  },
  {
    key: "tchalla",
    name: "T'Challa",
    alias: "Black Panther",
    description: "King of Wakanda and protector of its people, enhanced by the heart-shaped herb.",
    powers: ["Enhanced Strength", "Vibranium Suit", "Superhuman Agility", "Master Tactician"],
    stats: { strength: 70, intelligence: 85, speed: 75, durability: 80, energy: 40, combat: 95 },
    theme: { colorPrimary: "#4c1d95", colorSecondary: "#111827" },
    appearances: ["black-panther", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["steve-rogers", "shuri"],
    artifactsUsed: ["vibranium-suit"],
  },
  {
    key: "shuri",
    name: "Shuri",
    alias: "Princess of Wakanda",
    description:
      "T'Challa's younger sister and the technological genius behind Wakanda's vibranium innovations.",
    powers: ["Genius Intellect", "Engineering Mastery", "Combat Training"],
    stats: { strength: 40, intelligence: 100, speed: 55, durability: 45, energy: 35, combat: 65 },
    theme: { colorPrimary: "#7c3aed", colorSecondary: "#0f766e" },
    appearances: ["black-panther", "avengers-infinity-war"],
    affiliations: ["tchalla"],
    artifactsUsed: [],
  },
  {
    key: "peter-quill",
    name: "Peter Quill",
    alias: "Star-Lord",
    description:
      "A human abducted from Earth as a child who leads the Guardians of the Galaxy.",
    powers: ["Celestial Heritage", "Marksmanship", "Piloting", "Improvisation"],
    stats: { strength: 50, intelligence: 70, speed: 55, durability: 55, energy: 60, combat: 75 },
    theme: { colorPrimary: "#b45309", colorSecondary: "#1e40af" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["gamora", "rocket-raccoon", "groot"],
    artifactsUsed: [],
  },
  {
    key: "gamora",
    name: "Gamora",
    alias: "The Deadliest Woman in the Galaxy",
    description:
      "The adopted daughter of Thanos who turned against him to join the Guardians of the Galaxy.",
    powers: ["Enhanced Strength", "Master Assassin", "Swordsmanship"],
    stats: { strength: 65, intelligence: 75, speed: 70, durability: 65, energy: 30, combat: 95 },
    theme: { colorPrimary: "#15803d", colorSecondary: "#7f1d1d" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war"],
    affiliations: ["peter-quill", "thanos", "rocket-raccoon"],
    artifactsUsed: [],
  },
  {
    key: "rocket-raccoon",
    name: "Rocket",
    alias: "Rocket Raccoon",
    description:
      "A genetically engineered raccoon bounty hunter, expert in weapons and tactics.",
    powers: ["Weapons Expert", "Engineering Genius", "Marksmanship"],
    stats: { strength: 30, intelligence: 90, speed: 55, durability: 40, energy: 35, combat: 80 },
    theme: { colorPrimary: "#a16207", colorSecondary: "#1f2937" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["peter-quill", "groot", "thor-odinson"],
    artifactsUsed: [],
  },
  {
    key: "groot",
    name: "Groot",
    alias: "I am Groot",
    description: "A tree-like humanoid and Rocket's closest companion, capable of regrowth.",
    powers: ["Regeneration", "Body Manipulation", "Superhuman Strength"],
    stats: { strength: 85, intelligence: 40, speed: 40, durability: 90, energy: 45, combat: 65 },
    theme: { colorPrimary: "#4d7c0f", colorSecondary: "#78350f" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war"],
    affiliations: ["rocket-raccoon", "peter-quill"],
    artifactsUsed: [],
  },
  {
    key: "loki-laufeyson",
    name: "Loki Laufeyson",
    alias: "God of Mischief",
    description:
      "Thor's adopted brother, a Frost Giant raised in Asgard, whose loyalties shift constantly.",
    powers: ["Illusion Casting", "Shapeshifting", "Sorcery", "Longevity"],
    stats: { strength: 60, intelligence: 90, speed: 65, durability: 70, energy: 85, combat: 80 },
    theme: { colorPrimary: "#15803d", colorSecondary: "#a16207" },
    appearances: ["the-avengers", "thor-ragnarok", "avengers-infinity-war"],
    affiliations: ["thor-odinson"],
    artifactsUsed: ["tesseract"],
  },
  {
    key: "thanos",
    name: "Thanos",
    alias: "The Mad Titan",
    description:
      "A warlord from Titan who seeks the Infinity Stones to erase half of all life in the universe.",
    powers: ["Immense Strength", "Invulnerability", "Genius Tactician", "Energy Projection"],
    stats: { strength: 100, intelligence: 90, speed: 70, durability: 100, energy: 100, combat: 95 },
    theme: { colorPrimary: "#6d28d9", colorSecondary: "#a16207" },
    appearances: ["avengers-infinity-war", "avengers-endgame"],
    affiliations: ["gamora"],
    artifactsUsed: ["infinity-gauntlet"],
  },
];

export const artifacts = [
  {
    key: "infinity-gauntlet",
    name: "Infinity Gauntlet",
    description:
      "A gilded glove forged to harness all six Infinity Stones, granting its wearer power over reality itself.",
    origin: "Forged by Eitri on Nidavellir",
    powers: ["Reality Warping", "Time Manipulation", "Soul Control"],
    status: "destroyed",
    holders: ["thanos", "tony-stark"],
    appearances: ["avengers-infinity-war", "avengers-endgame"],
  },
  {
    key: "mjolnir",
    name: "Mjolnir",
    description:
      "Thor's enchanted hammer, forged in the heart of a dying star and liftable only by the worthy.",
    origin: "Forged in Nidavellir from Uru metal",
    powers: ["Worthiness Enchantment", "Lightning Summoning", "Flight"],
    status: "destroyed",
    holders: ["thor-odinson", "steve-rogers"],
    appearances: ["the-avengers", "thor-ragnarok", "avengers-endgame"],
  },
  {
    key: "stormbreaker",
    name: "Stormbreaker",
    description:
      "An axe forged to channel the full power of the Bifrost, capable of wounding Thanos.",
    origin: "Forged on Nidavellir during the Infinity War",
    powers: ["Bifrost Summoning", "Energy Channeling", "Flight"],
    status: "active",
    holders: ["thor-odinson"],
    appearances: ["avengers-infinity-war", "avengers-endgame"],
  },
  {
    key: "vibranium-shield",
    name: "Vibranium Shield",
    description:
      "Captain America's near-indestructible shield, capable of absorbing and redirecting kinetic energy.",
    origin: "Wakandan vibranium, forged by Howard Stark",
    powers: ["Kinetic Absorption", "Indestructibility"],
    status: "active",
    holders: ["steve-rogers", "sam-wilson"],
    appearances: ["the-avengers", "captain-america-the-winter-soldier", "avengers-endgame"],
  },
  {
    key: "tesseract",
    name: "Tesseract",
    description:
      "A crystalline cube housing the Space Stone, capable of opening portals across the universe.",
    origin: "Ancient cosmic artifact containing the Space Stone",
    powers: ["Space Manipulation", "Portal Creation", "Energy Source"],
    status: "destroyed",
    holders: ["loki-laufeyson", "thanos"],
    appearances: ["the-avengers", "avengers-infinity-war"],
  },
  {
    key: "eye-of-agamotto",
    name: "Eye of Agamotto",
    description:
      "A mystical relic containing the Time Stone, worn by the Sorcerer Supreme.",
    origin: "Created by Agamotto, the first Sorcerer Supreme",
    powers: ["Time Manipulation", "Temporal Loops"],
    status: "destroyed",
    holders: ["stephen-strange"],
    appearances: ["doctor-strange", "avengers-infinity-war"],
  },
  {
    key: "cloak-of-levitation",
    name: "Cloak of Levitation",
    description:
      "A sentient mystical garment that chooses its wearer and fights alongside them.",
    origin: "Relic of the New York Sanctum",
    powers: ["Flight", "Sentience", "Autonomous Defense"],
    status: "active",
    holders: ["stephen-strange"],
    appearances: ["doctor-strange", "avengers-infinity-war"],
  },
  {
    key: "arc-reactor",
    name: "Arc Reactor",
    description:
      "A miniaturized fusion power source that keeps Tony Stark alive and powers the Iron Man armor.",
    origin: "Built by Tony Stark in a cave in Afghanistan",
    powers: ["Clean Energy Generation", "Armor Power Source"],
    status: "active",
    holders: ["tony-stark"],
    appearances: ["iron-man", "the-avengers", "avengers-endgame"],
  },
  {
    key: "vibranium-suit",
    name: "Black Panther Habit",
    description:
      "A vibranium-weave suit that absorbs kinetic energy and releases it in a concussive blast.",
    origin: "Designed by Shuri in Wakanda",
    powers: ["Kinetic Absorption", "Energy Redistribution", "Nanotech Storage"],
    status: "active",
    holders: ["tchalla"],
    appearances: ["black-panther", "avengers-infinity-war"],
  },
];

export const teams = [
  {
    key: "avengers",
    name: "The Avengers",
    description:
      "Earth's mightiest heroes, assembled by Nick Fury to fight the battles no single hero could win.",
    headquarters: "Avengers Compound, Upstate New York",
    founded: "2012",
    status: "active",
    theme: { colorPrimary: "#c8102e", colorSecondary: "#0a3161" },
    leaders: ["steve-rogers", "tony-stark"],
    members: [
      "tony-stark",
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "natasha-romanoff",
      "clint-barton",
    ],
    appearances: ["the-avengers", "avengers-infinity-war", "avengers-endgame"],
  },
  {
    key: "guardians-of-the-galaxy-team",
    name: "Guardians of the Galaxy",
    description:
      "A band of intergalactic misfits who became the protectors of the cosmos.",
    headquarters: "The Milano",
    founded: "2014",
    status: "active",
    theme: { colorPrimary: "#b45309", colorSecondary: "#7c3aed" },
    leaders: ["peter-quill"],
    members: ["peter-quill", "gamora", "rocket-raccoon", "groot"],
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war"],
  },
  {
    key: "wakandan-royal-family",
    name: "Wakandan Royal Family",
    description:
      "The ruling line of Wakanda, guardians of the world's only vibranium deposit.",
    headquarters: "Golden City, Wakanda",
    founded: "Ancient",
    status: "active",
    theme: { colorPrimary: "#4c1d95", colorSecondary: "#0f766e" },
    leaders: ["tchalla"],
    members: ["tchalla", "shuri"],
    appearances: ["black-panther", "avengers-infinity-war"],
  },
];

export const battles = [
  {
    key: "battle-of-new-york",
    name: "Battle of New York",
    description:
      "Loki's Chitauri army invades Manhattan through a portal opened by the Tesseract, forcing the newly formed Avengers to fight as a team for the first time.",
    location: "Manhattan, New York City",
    significance: "major",
    outcome:
      "The Avengers close the portal and capture Loki. Tony Stark nearly dies redirecting a nuclear missile through the wormhole.",
    casualties: 74,
    movie: "the-avengers",
    participants: [
      "tony-stark",
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "natasha-romanoff",
      "clint-barton",
      "loki-laufeyson",
    ],
    winner: "steve-rogers",
  },
  {
    key: "highway-ambush",
    name: "Highway Ambush",
    description:
      "The Winter Soldier and HYDRA operatives ambush Steve Rogers, Natasha Romanoff and Sam Wilson on a Washington D.C. overpass.",
    location: "Washington, D.C.",
    significance: "minor",
    outcome:
      "The trio survive but are captured by S.H.I.E.L.D. forces loyal to HYDRA. Steve recognizes Bucky beneath the mask.",
    casualties: 12,
    movie: "captain-america-the-winter-soldier",
    participants: ["steve-rogers", "natasha-romanoff", "sam-wilson", "bucky-barnes"],
    winner: "bucky-barnes",
  },
  {
    key: "battle-of-xandar",
    name: "Battle of Xandar",
    description:
      "The newly formed Guardians confront Ronan the Accuser, who wields the Power Stone above Xandar's capital.",
    location: "Xandar, Nova Empire",
    significance: "major",
    outcome:
      "The Guardians share the Power Stone's burden between them and destroy Ronan, saving Xandar.",
    casualties: 0,
    movie: "guardians-of-the-galaxy",
    participants: ["peter-quill", "gamora", "rocket-raccoon", "groot"],
    winner: "peter-quill",
  },
  {
    key: "duel-at-the-hong-kong-sanctum",
    name: "Duel at the Hong Kong Sanctum",
    description:
      "Doctor Strange reverses time over a destroyed Hong Kong to undo Kaecilius' attack on the Sanctum.",
    location: "Hong Kong",
    significance: "major",
    outcome:
      "Strange rewinds time, restores the Sanctum, and bargains with Dormammu to save Earth.",
    casualties: 0,
    movie: "doctor-strange",
    participants: ["stephen-strange"],
    winner: "stephen-strange",
  },
  {
    key: "contest-of-champions",
    name: "Contest of Champions",
    description:
      "Thor is forced into gladiatorial combat on Sakaar against the Grandmaster's reigning champion - the Hulk.",
    location: "Sakaar",
    significance: "minor",
    outcome:
      "The fight ends in a draw when the Grandmaster intervenes. Thor and Bruce later escape together.",
    casualties: 0,
    movie: "thor-ragnarok",
    participants: ["thor-odinson", "bruce-banner"],
    winner: "bruce-banner",
  },
  {
    key: "challenge-at-warrior-falls",
    name: "Challenge at Warrior Falls",
    description:
      "Erik Killmonger invokes ritual combat to claim the Wakandan throne from T'Challa.",
    location: "Warrior Falls, Wakanda",
    significance: "major",
    outcome: "T'Challa is defeated and thrown from the falls; Killmonger takes the throne.",
    casualties: 3,
    movie: "black-panther",
    participants: ["tchalla"],
    winner: null,
  },
  {
    key: "battle-of-titan",
    name: "Battle of Titan",
    description:
      "Iron Man, Spider-Man, Doctor Strange and the Guardians confront Thanos on his ruined homeworld in a desperate attempt to remove the Gauntlet.",
    location: "Titan",
    significance: "universe-altering",
    outcome:
      "The plan fails when Star-Lord loses control. Thanos takes the Time Stone after Strange surrenders it to preserve the one winning future.",
    casualties: 0,
    movie: "avengers-infinity-war",
    participants: [
      "tony-stark",
      "peter-parker",
      "stephen-strange",
      "peter-quill",
      "gamora",
      "thanos",
    ],
    winner: "thanos",
  },
  {
    key: "battle-of-wakanda",
    name: "Battle of Wakanda",
    description:
      "Thanos' Outriders assault Wakanda's shield in a bid to tear the Mind Stone from Vision's forehead.",
    location: "Golden City, Wakanda",
    significance: "universe-altering",
    outcome:
      "Thanos arrives, takes the Mind Stone, and snaps. Half of all life in the universe turns to dust.",
    casualties: 2000,
    movie: "avengers-infinity-war",
    participants: [
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "natasha-romanoff",
      "tchalla",
      "shuri",
      "bucky-barnes",
      "sam-wilson",
      "rocket-raccoon",
      "groot",
      "thanos",
    ],
    winner: "thanos",
  },
  {
    key: "battle-of-earth",
    name: "Battle of Earth",
    description:
      "Every surviving hero returns through Strange's portals for a final stand against Thanos and his armada at the ruined Avengers Compound.",
    location: "Avengers Compound, Upstate New York",
    significance: "universe-altering",
    outcome:
      "Tony Stark seizes the Infinity Stones and snaps Thanos' army out of existence, sacrificing his own life.",
    casualties: 500,
    movie: "avengers-endgame",
    participants: [
      "tony-stark",
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "clint-barton",
      "peter-parker",
      "stephen-strange",
      "tchalla",
      "peter-quill",
      "rocket-raccoon",
      "groot",
      "thanos",
    ],
    winner: "tony-stark",
  },
];
