/**
 * Curated MCU sample data.
 *
 * Entities reference each other by a stable `key` (a slug), never by ObjectId -
 * the loader resolves keys to ids in a second pass. That keeps this file
 * hand-editable and makes re-running the seed idempotent.
 */

export const movies = [
  {
    key: "iron-man",
    title: "Iron Man",
    releaseYear: 2008,
    phase: "Phase 1",
    director: "Jon Favreau",
    runtime: 126,
    rating: 7.9,
    boxOffice: 585796247,
    synopsis:
      "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
  },
  {
    key: "the-incredible-hulk",
    title: "The Incredible Hulk",
    releaseYear: 2008,
    phase: "Phase 1",
  },
  {
    key: "iron-man-2",
    title: "Iron Man 2",
    releaseYear: 2010,
    phase: "Phase 1",
  },
  {
    key: "thor",
    title: "Thor",
    releaseYear: 2011,
    phase: "Phase 1",
  },
  {
    key: "captain-america-the-first-avenger",
    title: "Captain America: The First Avenger",
    releaseYear: 2011,
    phase: "Phase 1",
  },
  {
    key: "the-avengers",
    title: "The Avengers",
    releaseYear: 2012,
    phase: "Phase 1",
    director: "Joss Whedon",
    runtime: 143,
    rating: 8.0,
    boxOffice: 1518815515,
    synopsis:
      "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.",
  },
  {
    key: "iron-man-3",
    title: "Iron Man 3",
    releaseYear: 2013,
    phase: "Phase 2",
  },
  {
    key: "thor-the-dark-world",
    title: "Thor: The Dark World",
    releaseYear: 2013,
    phase: "Phase 2",
  },
  {
    key: "captain-america-the-winter-soldier",
    title: "Captain America: The Winter Soldier",
    releaseYear: 2014,
    phase: "Phase 2",
    director: "Anthony and Joe Russo",
    runtime: 136,
    rating: 7.7,
    boxOffice: 714421503,
    synopsis:
      "Steve Rogers struggles to embrace his role in the modern world and battles a new threat from old history: the Winter Soldier.",
  },
  {
    key: "guardians-of-the-galaxy",
    title: "Guardians of the Galaxy",
    releaseYear: 2014,
    phase: "Phase 2",
    director: "James Gunn",
    runtime: 121,
    rating: 8.0,
    boxOffice: 772776600,
    synopsis:
      "A group of intergalactic criminals must pull together to stop a fanatical warrior from taking control of the universe.",
  },
  {
    key: "avengers-age-of-ultron",
    title: "Avengers: Age of Ultron",
    releaseYear: 2015,
    phase: "Phase 2",
  },
  {
    key: "ant-man",
    title: "Ant-Man",
    releaseYear: 2015,
    phase: "Phase 2",
  },
  {
    key: "captain-america-civil-war",
    title: "Captain America: Civil War",
    releaseYear: 2016,
    phase: "Phase 3",
  },
  {
    key: "doctor-strange",
    title: "Doctor Strange",
    releaseYear: 2016,
    phase: "Phase 3",
    director: "Scott Derrickson",
    runtime: 115,
    rating: 7.5,
    boxOffice: 677718395,
    synopsis:
      "A neurosurgeon discovers the hidden world of magic and alternate dimensions after a career-ending car accident.",
  },
  {
    key: "guardians-of-the-galaxy-vol-2",
    title: "Guardians of the Galaxy Vol. 2",
    releaseYear: 2017,
    phase: "Phase 3",
  },
  {
    key: "spider-man-homecoming",
    title: "Spider-Man: Homecoming",
    releaseYear: 2017,
    phase: "Phase 3",
  },
  {
    key: "thor-ragnarok",
    title: "Thor: Ragnarok",
    releaseYear: 2017,
    phase: "Phase 3",
    director: "Taika Waititi",
    runtime: 130,
    rating: 7.9,
    boxOffice: 854229371,
    synopsis:
      "Imprisoned on Sakaar, Thor must race against time to return to Asgard and stop Hela and the destruction of his world.",
  },
  {
    key: "black-panther",
    title: "Black Panther",
    releaseYear: 2018,
    phase: "Phase 3",
    director: "Ryan Coogler",
    runtime: 134,
    rating: 7.3,
    boxOffice: 1347280838,
    synopsis:
      "T'Challa returns home to Wakanda to take his place as king, but a powerful enemy reappears to challenge the throne.",
  },
  {
    key: "avengers-infinity-war",
    title: "Avengers: Infinity War",
    releaseYear: 2018,
    phase: "Phase 3",
    director: "Anthony and Joe Russo",
    runtime: 149,
    rating: 8.4,
    boxOffice: 2048359754,
    synopsis:
      "The Avengers must stop Thanos from collecting all six Infinity Stones and wiping out half of all life.",
  },
  {
    key: "ant-man-and-the-wasp",
    title: "Ant-Man and the Wasp",
    releaseYear: 2018,
    phase: "Phase 3",
  },
  {
    key: "captain-marvel",
    title: "Captain Marvel",
    releaseYear: 2019,
    phase: "Phase 3",
  },
  {
    key: "avengers-endgame",
    title: "Avengers: Endgame",
    releaseYear: 2019,
    phase: "Phase 3",
    director: "Anthony and Joe Russo",
    runtime: 181,
    rating: 8.4,
    boxOffice: 2799439100,
    synopsis:
      "After the devastating events of Infinity War, the remaining Avengers take one final stand to undo Thanos' snap.",
  },
  {
    key: "spider-man-far-from-home",
    title: "Spider-Man: Far From Home",
    releaseYear: 2019,
    phase: "Phase 3",
  },
  {
    key: "black-widow",
    title: "Black Widow",
    releaseYear: 2021,
    phase: "Phase 4",
  },
  {
    key: "shang-chi-and-the-legend-of-the-ten-rings",
    title: "Shang-Chi and the Legend of the Ten Rings",
    releaseYear: 2021,
    phase: "Phase 4",
  },
  {
    key: "eternals",
    title: "Eternals",
    releaseYear: 2021,
    phase: "Phase 4",
  },
  {
    key: "spider-man-no-way-home",
    title: "Spider-Man: No Way Home",
    releaseYear: 2021,
    phase: "Phase 4",
  },
  {
    key: "doctor-strange-in-the-multiverse-of-madness",
    title: "Doctor Strange in the Multiverse of Madness",
    releaseYear: 2022,
    phase: "Phase 4",
  },
  {
    key: "thor-love-and-thunder",
    title: "Thor: Love and Thunder",
    releaseYear: 2022,
    phase: "Phase 4",
  },
  {
    key: "black-panther-wakanda-forever",
    title: "Black Panther: Wakanda Forever",
    releaseYear: 2022,
    phase: "Phase 4",
  },
  {
    key: "ant-man-and-the-wasp-quantumania",
    title: "Ant-Man and the Wasp: Quantumania",
    releaseYear: 2023,
    phase: "Phase 5",
  },
  {
    key: "guardians-of-the-galaxy-vol-3",
    title: "Guardians of the Galaxy Vol. 3",
    releaseYear: 2023,
    phase: "Phase 5",
  },
  {
    key: "the-marvels",
    title: "The Marvels",
    releaseYear: 2023,
    phase: "Phase 5",
  },
  {
    key: "deadpool-and-wolverine",
    title: "Deadpool & Wolverine",
    releaseYear: 2024,
    phase: "Phase 5",
  },
  {
    key: "captain-america-brave-new-world",
    title: "Captain America: Brave New World",
    releaseYear: 2025,
    phase: "Phase 5",
  },
  {
    key: "thunderbolts",
    title: "Thunderbolts*",
    releaseYear: 2025,
    phase: "Phase 5",
  },
  {
    key: "the-fantastic-four-first-steps",
    title: "The Fantastic Four: First Steps",
    releaseYear: 2025,
    phase: "Phase 6",
  },
  {
    key: "spider-man-brand-new-day",
    title: "Spider-Man: Brand New Day",
    releaseYear: 2026,
    phase: "Phase 6",
  },
];

export const characters = [
  {
    key: "tony-stark",
    name: "Tony Stark",
    alias: "Iron Man",
    description:
      "Genius, billionaire, playboy, philanthropist. Founder of Stark Industries and a founding member of the Avengers.",
    powers: ["Powered Armor", "Genius Intellect", "Flight", "Repulsor Blasts"],
    theme: { colorPrimary: "#c8102e", colorSecondary: "#f0a500" },
    appearances: [
      "iron-man",
      "iron-man-2",
      "the-avengers",
      "iron-man-3",
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "spider-man-homecoming",
      "avengers-infinity-war",
      "avengers-endgame",
    ],
    affiliations: [
      "steve-rogers",
      "bruce-banner",
      "peter-parker",
      "stephen-strange",
      "pepper-potts",
      "james-rhodes",
      "happy-hogan",
      "vision",
    ],
    artifactsUsed: ["arc-reactor", "infinity-gauntlet"],
  },
  {
    key: "steve-rogers",
    name: "Steve Rogers",
    alias: "Captain America",
    description:
      "The first Avenger. A World War II super soldier who became the moral center of Earth's mightiest heroes.",
    powers: ["Super Soldier Serum", "Peak Human Strength", "Shield Mastery", "Tactical Genius"],
    theme: { colorPrimary: "#0a3161", colorSecondary: "#c8102e" },
    appearances: [
      "captain-america-the-first-avenger",
      "the-avengers",
      "captain-america-the-winter-soldier",
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "spider-man-homecoming",
      "avengers-infinity-war",
      "avengers-endgame",
    ],
    affiliations: [
      "tony-stark",
      "natasha-romanoff",
      "bucky-barnes",
      "sam-wilson",
      "peggy-carter",
      "nick-fury",
      "scott-lang",
      "wanda-maximoff",
    ],
    artifactsUsed: ["vibranium-shield", "mjolnir"],
  },
  {
    key: "thor-odinson",
    name: "Thor Odinson",
    alias: "Thor",
    description:
      "The God of Thunder and rightful king of Asgard. Wielder of Mjolnir and later Stormbreaker.",
    powers: ["Godly Strength", "Weather Manipulation", "Flight", "Longevity"],
    theme: { colorPrimary: "#1e3a8a", colorSecondary: "#dc2626" },
    appearances: ["the-avengers", "thor-ragnarok", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["loki-laufeyson", "bruce-banner", "tony-stark"],
    artifactsUsed: ["mjolnir", "stormbreaker"],
  },
  {
    key: "bruce-banner",
    name: "Bruce Banner",
    alias: "Hulk",
    description:
      "A brilliant physicist whose exposure to gamma radiation transforms him into an unstoppable green giant.",
    powers: ["Superhuman Strength", "Regeneration", "Genius Intellect", "Limitless Rage"],
    theme: { colorPrimary: "#15803d", colorSecondary: "#581c87" },
    appearances: [
      "the-incredible-hulk",
      "the-avengers",
      "avengers-age-of-ultron",
      "thor-ragnarok",
      "avengers-infinity-war",
      "avengers-endgame",
      "captain-america-brave-new-world",
    ],
    affiliations: [
      "tony-stark",
      "thor-odinson",
      "natasha-romanoff",
      "vision",
    ],
    artifactsUsed: [],
  },
  {
    key: "natasha-romanoff",
    name: "Natasha Romanoff",
    alias: "Black Widow",
    description:
      "A former KGB assassin turned S.H.I.E.L.D. agent and founding Avenger, deadly without any powers.",
    powers: ["Master Assassin", "Espionage", "Acrobatics", "Multilingual"],
    theme: { colorPrimary: "#7f1d1d", colorSecondary: "#111827" },
    appearances: [
      "iron-man-2",
      "the-avengers",
      "captain-america-the-winter-soldier",
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "avengers-infinity-war",
      "avengers-endgame",
      "black-widow",
    ],
    affiliations: [
      "steve-rogers",
      "bruce-banner",
      "clint-barton",
      "nick-fury",
      "maria-hill",
      "james-rhodes",
    ],
    artifactsUsed: [],
  },
  {
    key: "clint-barton",
    name: "Clint Barton",
    alias: "Hawkeye",
    description: "A master marksman and S.H.I.E.L.D. agent who never misses his target.",
    powers: ["Master Archer", "Marksmanship", "Hand-to-Hand Combat"],
    theme: { colorPrimary: "#4c1d95", colorSecondary: "#111827" },
    appearances: [
      "thor",
      "the-avengers",
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "avengers-endgame",
    ],
    affiliations: [
      "natasha-romanoff",
      "steve-rogers",
      "scott-lang",
    ],
    artifactsUsed: [],
  },
  {
    key: "bucky-barnes",
    name: "Bucky Barnes",
    alias: "Winter Soldier",
    description:
      "Steve Rogers' closest friend, brainwashed into a HYDRA assassin before reclaiming his identity.",
    powers: ["Enhanced Strength", "Bionic Arm", "Master Marksman", "Espionage"],
    theme: { colorPrimary: "#374151", colorSecondary: "#7f1d1d" },
    appearances: [
      "captain-america-the-first-avenger",
      "captain-america-the-winter-soldier",
      "captain-america-civil-war",
      "avengers-infinity-war",
      "avengers-endgame",
      "thunderbolts",
    ],
    affiliations: [
      "steve-rogers",
      "sam-wilson",
      "peggy-carter",
    ],
    artifactsUsed: [],
  },
  {
    key: "sam-wilson",
    name: "Sam Wilson",
    alias: "Falcon",
    description:
      "A former pararescue airman who fights alongside Captain America with a winged flight suit.",
    powers: ["Flight", "Aerial Combat", "Military Training"],
    theme: { colorPrimary: "#b91c1c", colorSecondary: "#f3f4f6" },
    appearances: [
      "captain-america-the-winter-soldier",
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "avengers-infinity-war",
      "avengers-endgame",
      "captain-america-brave-new-world",
    ],
    affiliations: [
      "steve-rogers",
      "bucky-barnes",
      "james-rhodes",
      "sharon-carter",
    ],
    artifactsUsed: [],
  },
  {
    key: "peter-parker",
    name: "Peter Parker",
    alias: "Spider-Man",
    description:
      "A teenage genius from Queens with the proportionate abilities of a spider, mentored by Tony Stark.",
    powers: ["Wall-Crawling", "Spider-Sense", "Superhuman Agility", "Genius Intellect"],
    theme: { colorPrimary: "#dc2626", colorSecondary: "#1d4ed8" },
    appearances: [
      "captain-america-civil-war",
      "spider-man-homecoming",
      "avengers-infinity-war",
      "avengers-endgame",
      "spider-man-far-from-home",
      "spider-man-no-way-home",
      "spider-man-brand-new-day",
    ],
    affiliations: [
      "tony-stark",
      "stephen-strange",
      "happy-hogan",
    ],
    artifactsUsed: [],
  },
  {
    key: "stephen-strange",
    name: "Stephen Strange",
    alias: "Doctor Strange",
    description:
      "A former neurosurgeon who became Master of the Mystic Arts and guardian of the Time Stone.",
    powers: ["Sorcery", "Astral Projection", "Time Manipulation", "Portal Creation"],
    theme: { colorPrimary: "#b45309", colorSecondary: "#7f1d1d" },
    appearances: ["doctor-strange", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["tony-stark", "peter-parker"],
    artifactsUsed: ["eye-of-agamotto", "cloak-of-levitation"],
  },
  {
    key: "tchalla",
    name: "T'Challa",
    alias: "Black Panther",
    description: "King of Wakanda and protector of its people, enhanced by the heart-shaped herb.",
    powers: ["Enhanced Strength", "Vibranium Suit", "Superhuman Agility", "Master Tactician"],
    theme: { colorPrimary: "#4c1d95", colorSecondary: "#111827" },
    appearances: ["black-panther", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["steve-rogers", "shuri"],
    artifactsUsed: ["vibranium-suit"],
  },
  {
    key: "shuri",
    name: "Shuri",
    alias: "Princess of Wakanda",
    description:
      "T'Challa's younger sister and the technological genius behind Wakanda's vibranium innovations.",
    powers: ["Genius Intellect", "Engineering Mastery", "Combat Training"],
    theme: { colorPrimary: "#7c3aed", colorSecondary: "#0f766e" },
    appearances: ["black-panther", "avengers-infinity-war"],
    affiliations: ["tchalla"],
    artifactsUsed: [],
  },
  {
    key: "peter-quill",
    name: "Peter Quill",
    alias: "Star-Lord",
    description:
      "A human abducted from Earth as a child who leads the Guardians of the Galaxy.",
    powers: ["Celestial Heritage", "Marksmanship", "Piloting", "Improvisation"],
    theme: { colorPrimary: "#b45309", colorSecondary: "#1e40af" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["gamora", "rocket-raccoon", "groot"],
    artifactsUsed: [],
  },
  {
    key: "gamora",
    name: "Gamora",
    alias: "The Deadliest Woman in the Galaxy",
    description:
      "The adopted daughter of Thanos who turned against him to join the Guardians of the Galaxy.",
    powers: ["Enhanced Strength", "Master Assassin", "Swordsmanship"],
    theme: { colorPrimary: "#15803d", colorSecondary: "#7f1d1d" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war"],
    affiliations: ["peter-quill", "thanos", "rocket-raccoon"],
    artifactsUsed: [],
  },
  {
    key: "rocket-raccoon",
    name: "Rocket",
    alias: "Rocket Raccoon",
    description:
      "A genetically engineered raccoon bounty hunter, expert in weapons and tactics.",
    powers: ["Weapons Expert", "Engineering Genius", "Marksmanship"],
    theme: { colorPrimary: "#a16207", colorSecondary: "#1f2937" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war", "avengers-endgame"],
    affiliations: ["peter-quill", "groot", "thor-odinson"],
    artifactsUsed: [],
  },
  {
    key: "groot",
    name: "Groot",
    alias: "I am Groot",
    description: "A tree-like humanoid and Rocket's closest companion, capable of regrowth.",
    powers: ["Regeneration", "Body Manipulation", "Superhuman Strength"],
    theme: { colorPrimary: "#4d7c0f", colorSecondary: "#78350f" },
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war"],
    affiliations: ["rocket-raccoon", "peter-quill"],
    artifactsUsed: [],
  },
  {
    key: "loki-laufeyson",
    name: "Loki Laufeyson",
    alias: "God of Mischief",
    description:
      "Thor's adopted brother, a Frost Giant raised in Asgard, whose loyalties shift constantly.",
    powers: ["Illusion Casting", "Shapeshifting", "Sorcery", "Longevity"],
    theme: { colorPrimary: "#15803d", colorSecondary: "#a16207" },
    appearances: ["the-avengers", "thor-ragnarok", "avengers-infinity-war"],
    affiliations: ["thor-odinson"],
    artifactsUsed: ["tesseract"],
  },
  {
    key: "thanos",
    name: "Thanos",
    alias: "The Mad Titan",
    description:
      "A warlord from Titan who seeks the Infinity Stones to erase half of all life in the universe.",
    powers: ["Immense Strength", "Invulnerability", "Genius Tactician", "Energy Projection"],
    theme: { colorPrimary: "#6d28d9", colorSecondary: "#a16207" },
    appearances: ["avengers-infinity-war", "avengers-endgame"],
    affiliations: ["gamora"],
    artifactsUsed: ["infinity-gauntlet"],
  },
  // --- Iron Man / Stark cluster -------------------------------------------
  {
    key: "pepper-potts",
    name: "Pepper Potts",
    alias: "Rescue",
    description:
      "Stark Industries CEO and Tony Stark's partner. Ran the company while he was Iron Man, and eventually took the field herself in the Rescue armor.",
    powers: ["Powered Armor", "Business Acumen", "Strategic Leadership"],
    theme: { colorPrimary: "#c8102e", colorSecondary: "#60a5fa" },
    appearances: [
      "iron-man",
      "iron-man-2",
      "the-avengers",
      "iron-man-3",
      "spider-man-homecoming",
      "avengers-infinity-war",
      "avengers-endgame",
    ],
    affiliations: ["tony-stark", "james-rhodes", "happy-hogan"],
    artifactsUsed: ["arc-reactor"],
  },
  {
    key: "james-rhodes",
    name: "James Rhodes",
    alias: "War Machine",
    description:
      "Air Force colonel and Tony Stark's oldest friend. Pilots the War Machine armor as the military's answer to Iron Man.",
    powers: ["Powered Armor", "Heavy Weaponry", "Military Tactics", "Flight"],
    theme: { colorPrimary: "#4b5563", colorSecondary: "#c8102e" },
    appearances: [
      "iron-man",
      "iron-man-2",
      "iron-man-3",
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "avengers-infinity-war",
      "avengers-endgame",
      "captain-america-brave-new-world",
    ],
    affiliations: ["tony-stark", "pepper-potts", "sam-wilson", "natasha-romanoff"],
    artifactsUsed: [],
  },
  {
    key: "happy-hogan",
    name: "Happy Hogan",
    alias: "Head of Security",
    description:
      "Stark's driver turned head of security. Became a reluctant mentor to Peter Parker after Tony's death.",
    powers: ["Hand-to-Hand Combat", "Security Expertise"],
    theme: { colorPrimary: "#a16207", colorSecondary: "#c8102e" },
    appearances: [
      "iron-man",
      "iron-man-2",
      "iron-man-3",
      "spider-man-homecoming",
      "avengers-endgame",
      "spider-man-far-from-home",
      "spider-man-no-way-home",
    ],
    affiliations: ["tony-stark", "pepper-potts", "peter-parker"],
    artifactsUsed: [],
  },
  {
    key: "howard-stark",
    name: "Howard Stark",
    alias: "Founder of Stark Industries",
    description:
      "Industrialist, weapons designer and founding member of S.H.I.E.L.D. Built the equipment that made Captain America possible, and fathered the man who became Iron Man.",
    powers: ["Genius Intellect", "Engineering Mastery"],
    theme: { colorPrimary: "#a16207", colorSecondary: "#0a3161" },
    appearances: [
      "captain-america-the-first-avenger",
      "iron-man-2",
      "ant-man",
      "captain-america-civil-war",
      "avengers-endgame",
    ],
    affiliations: ["tony-stark", "steve-rogers", "peggy-carter", "hank-pym"],
    artifactsUsed: ["tesseract", "vibranium-shield"],
  },
  {
    key: "obadiah-stane",
    name: "Obadiah Stane",
    alias: "Iron Monger",
    description:
      "Stark Industries executive who ordered Tony's assassination and built the Iron Monger suit from the scraps of his captors' work.",
    powers: ["Powered Armor", "Corporate Manipulation", "Weapons Engineering"],
    theme: { colorPrimary: "#57534e", colorSecondary: "#a16207" },
    appearances: ["iron-man"],
    affiliations: ["tony-stark"],
    artifactsUsed: ["arc-reactor"],
  },
  {
    key: "ho-yinsen",
    name: "Ho Yinsen",
    alias: "The Man Who Saved Tony Stark",
    description:
      "Physicist held captive alongside Tony in Afghanistan. Built the first arc reactor into Tony's chest and died buying him the seconds to escape.",
    powers: ["Surgical Skill", "Engineering"],
    theme: { colorPrimary: "#78716c", colorSecondary: "#c8102e" },
    appearances: ["iron-man"],
    affiliations: ["tony-stark"],
    artifactsUsed: ["arc-reactor"],
  },
  {
    key: "ivan-vanko",
    name: "Ivan Vanko",
    alias: "Whiplash",
    description:
      "Russian physicist who blamed the Starks for his father's ruin and built arc-reactor-powered energy whips to settle it.",
    powers: ["Energy Whips", "Physics Expertise", "Powered Armor"],
    theme: { colorPrimary: "#1e293b", colorSecondary: "#22d3ee" },
    appearances: ["iron-man-2"],
    affiliations: ["tony-stark", "justin-hammer"],
    artifactsUsed: ["arc-reactor"],
  },
  {
    key: "justin-hammer",
    name: "Justin Hammer",
    alias: "Hammer Industries",
    description:
      "Rival defense contractor whose envy of Stark led him to free Ivan Vanko and hand him a weapons lab.",
    powers: ["Corporate Resources", "Weapons Manufacturing"],
    theme: { colorPrimary: "#64748b", colorSecondary: "#eab308" },
    appearances: ["iron-man-2"],
    affiliations: ["ivan-vanko", "tony-stark"],
    artifactsUsed: [],
  },
  {
    key: "aldrich-killian",
    name: "Aldrich Killian",
    alias: "The Mandarin",
    description:
      "A.I.M. founder who weaponised the Extremis virus and invented a terrorist figurehead to cover the fallout.",
    powers: ["Extremis Enhancement", "Regeneration", "Superheated Body", "Genius Intellect"],
    theme: { colorPrimary: "#ea580c", colorSecondary: "#7f1d1d" },
    appearances: ["iron-man-3"],
    affiliations: ["tony-stark", "trevor-slattery"],
    artifactsUsed: [],
  },
  {
    key: "trevor-slattery",
    name: "Trevor Slattery",
    alias: "The Mandarin (Actor)",
    description:
      "Failed stage actor hired to play the Mandarin on camera, later imprisoned and then rescued by the real Ten Rings.",
    powers: ["Acting"],
    theme: { colorPrimary: "#b45309", colorSecondary: "#78350f" },
    appearances: ["iron-man-3", "shang-chi-and-the-legend-of-the-ten-rings"],
    affiliations: ["aldrich-killian"],
    artifactsUsed: [],
  },
  {
    key: "harley-keener",
    name: "Harley Keener",
    alias: "The Kid from Rose Hill",
    description:
      "Tennessee boy who helped Tony rebuild after the Mandarin attack, and stood at his funeral years later.",
    powers: ["Improvised Engineering"],
    theme: { colorPrimary: "#c8102e", colorSecondary: "#0284c7" },
    appearances: ["iron-man-3", "avengers-endgame"],
    affiliations: ["tony-stark"],
    artifactsUsed: [],
  },
  {
    key: "vision",
    name: "Vision",
    alias: "The Vision",
    description:
      "A synthetic being born from JARVIS, Ultron's body and the Mind Stone. Lifted Mjolnir without effort and died twice on the same day.",
    powers: ["Density Manipulation", "Flight", "Mind Stone Beam", "Superhuman Analytics"],
    theme: { colorPrimary: "#dc2626", colorSecondary: "#fbbf24" },
    appearances: [
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "avengers-infinity-war",
    ],
    affiliations: ["tony-stark", "wanda-maximoff", "steve-rogers", "bruce-banner"],
    artifactsUsed: [],
  },
  {
    key: "wanda-maximoff",
    name: "Wanda Maximoff",
    alias: "Scarlet Witch",
    description:
      "Sokovian volunteer whose exposure to the Mind Stone unlocked reality-warping power. Grief made her the most dangerous being on Earth.",
    powers: ["Chaos Magic", "Telekinesis", "Reality Warping", "Mind Manipulation"],
    theme: { colorPrimary: "#dc2626", colorSecondary: "#1e1b4b" },
    appearances: [
      "avengers-age-of-ultron",
      "captain-america-civil-war",
      "avengers-infinity-war",
      "avengers-endgame",
      "doctor-strange-in-the-multiverse-of-madness",
    ],
    affiliations: ["vision", "steve-rogers", "natasha-romanoff", "stephen-strange"],
    artifactsUsed: [],
  },
  {
    key: "ultron",
    name: "Ultron",
    alias: "Ultron",
    description:
      "A peacekeeping intelligence built by Stark and Banner that concluded within seconds that peace required human extinction.",
    powers: [
      "Artificial Intelligence",
      "Robotic Body",
      "Flight",
      "Energy Blasts",
      "Self-Replication",
    ],
    theme: { colorPrimary: "#dc2626", colorSecondary: "#334155" },
    appearances: ["avengers-age-of-ultron"],
    affiliations: ["tony-stark", "bruce-banner", "wanda-maximoff"],
    artifactsUsed: [],
  },

  // --- Captain America / S.H.I.E.L.D. cluster ------------------------------
  {
    key: "peggy-carter",
    name: "Peggy Carter",
    alias: "Agent Carter",
    description:
      "SSR officer who ran the super soldier programme and co-founded S.H.I.E.L.D. The bridge between the war that made Captain America and the world he woke up in.",
    powers: ["Espionage", "Hand-to-Hand Combat", "Tactical Command", "Marksmanship"],
    theme: { colorPrimary: "#0a3161", colorSecondary: "#b91c1c" },
    appearances: [
      "captain-america-the-first-avenger",
      "captain-america-the-winter-soldier",
      "avengers-endgame",
    ],
    affiliations: ["steve-rogers", "howard-stark", "bucky-barnes", "chester-phillips"],
    artifactsUsed: [],
  },
  {
    key: "nick-fury",
    name: "Nick Fury",
    alias: "Director of S.H.I.E.L.D.",
    description:
      "The spymaster who assembled the Avengers. Spent decades deciding what everyone else was allowed to know.",
    powers: ["Espionage", "Tactical Command", "Marksmanship", "Manipulation"],
    theme: { colorPrimary: "#1e293b", colorSecondary: "#dc2626" },
    appearances: [
      "iron-man",
      "iron-man-2",
      "thor",
      "the-avengers",
      "captain-america-the-winter-soldier",
      "avengers-age-of-ultron",
      "avengers-infinity-war",
      "captain-marvel",
      "avengers-endgame",
      "spider-man-far-from-home",
      "the-marvels",
    ],
    affiliations: ["steve-rogers", "natasha-romanoff", "maria-hill", "phil-coulson", "tony-stark"],
    artifactsUsed: ["tesseract"],
  },
  {
    key: "maria-hill",
    name: "Maria Hill",
    alias: "Agent Hill",
    description:
      "Fury's second in command, and the officer who kept S.H.I.E.L.D. running when it turned out to be HYDRA underneath.",
    powers: ["Espionage", "Tactical Command", "Marksmanship"],
    theme: { colorPrimary: "#334155", colorSecondary: "#0ea5e9" },
    appearances: [
      "the-avengers",
      "captain-america-the-winter-soldier",
      "avengers-age-of-ultron",
      "avengers-infinity-war",
      "avengers-endgame",
      "spider-man-far-from-home",
    ],
    affiliations: ["nick-fury", "steve-rogers", "natasha-romanoff"],
    artifactsUsed: [],
  },
  {
    key: "phil-coulson",
    name: "Phil Coulson",
    alias: "Agent Coulson",
    description:
      "The S.H.I.E.L.D. agent whose death gave the Avengers a reason to stand together.",
    powers: ["Espionage", "Marksmanship", "Tactical Analysis"],
    theme: { colorPrimary: "#475569", colorSecondary: "#c8102e" },
    appearances: ["iron-man", "iron-man-2", "thor", "the-avengers"],
    affiliations: ["nick-fury", "steve-rogers", "tony-stark", "maria-hill"],
    artifactsUsed: [],
  },
  {
    key: "red-skull",
    name: "Johann Schmidt",
    alias: "Red Skull",
    description:
      "HYDRA's founder and the serum's first, worst success. Banished to Vormir as the Soul Stone's keeper.",
    powers: ["Super Soldier Serum", "Genius Intellect", "Tactical Command"],
    theme: { colorPrimary: "#7f1d1d", colorSecondary: "#000000" },
    appearances: [
      "captain-america-the-first-avenger",
      "avengers-infinity-war",
      "avengers-endgame",
    ],
    affiliations: ["steve-rogers", "arnim-zola", "howard-stark"],
    artifactsUsed: ["tesseract"],
  },
  {
    key: "arnim-zola",
    name: "Arnim Zola",
    alias: "The HYDRA Algorithm",
    description:
      "HYDRA scientist who survived his own death as a computer, and quietly rebuilt the organisation inside S.H.I.E.L.D.",
    powers: ["Genius Intellect", "Consciousness Transfer", "Bioengineering"],
    theme: { colorPrimary: "#166534", colorSecondary: "#1e293b" },
    appearances: ["captain-america-the-first-avenger", "captain-america-the-winter-soldier"],
    affiliations: ["red-skull", "bucky-barnes", "alexander-pierce"],
    artifactsUsed: [],
  },
  {
    key: "alexander-pierce",
    name: "Alexander Pierce",
    alias: "Secretary Pierce",
    description:
      "World Security Council head and Fury's old friend, running HYDRA from the top floor of S.H.I.E.L.D.",
    powers: ["Political Influence", "Manipulation", "Tactical Command"],
    theme: { colorPrimary: "#1e3a8a", colorSecondary: "#166534" },
    appearances: ["captain-america-the-winter-soldier", "avengers-endgame"],
    affiliations: ["nick-fury", "arnim-zola", "brock-rumlow", "steve-rogers"],
    artifactsUsed: [],
  },
  {
    key: "brock-rumlow",
    name: "Brock Rumlow",
    alias: "Crossbones",
    description:
      "STRIKE team leader and HYDRA loyalist who survived the Triskelion and came back for revenge in Lagos.",
    powers: ["Hand-to-Hand Combat", "Tactical Training", "Heavy Weaponry"],
    theme: { colorPrimary: "#292524", colorSecondary: "#b91c1c" },
    appearances: ["captain-america-the-winter-soldier", "captain-america-civil-war"],
    affiliations: ["alexander-pierce", "steve-rogers"],
    artifactsUsed: [],
  },
  {
    key: "sharon-carter",
    name: "Sharon Carter",
    alias: "Agent 13",
    description:
      "S.H.I.E.L.D. agent and Peggy's great-niece, who broke with the agency to help Steve Rogers when the Accords made him a fugitive.",
    powers: ["Espionage", "Hand-to-Hand Combat", "Marksmanship"],
    theme: { colorPrimary: "#1d4ed8", colorSecondary: "#c8102e" },
    appearances: ["captain-america-the-winter-soldier", "captain-america-civil-war"],
    affiliations: ["steve-rogers", "peggy-carter", "sam-wilson"],
    artifactsUsed: [],
  },
  {
    key: "chester-phillips",
    name: "Chester Phillips",
    alias: "Colonel Phillips",
    description:
      "The officer who ran the SSR and thought Steve Rogers was a waste of a serum, right up until he wasn't.",
    powers: ["Military Command", "Tactical Strategy"],
    theme: { colorPrimary: "#3f6212", colorSecondary: "#a16207" },
    appearances: ["captain-america-the-first-avenger"],
    affiliations: ["steve-rogers", "peggy-carter", "howard-stark", "abraham-erskine"],
    artifactsUsed: [],
  },
  {
    key: "abraham-erskine",
    name: "Abraham Erskine",
    alias: "Creator of the Super Soldier Serum",
    description:
      "The scientist who chose Steve Rogers precisely because he had never been strong, and was shot before he could write the formula down.",
    powers: ["Biochemistry", "Genius Intellect"],
    theme: { colorPrimary: "#0e7490", colorSecondary: "#a16207" },
    appearances: ["captain-america-the-first-avenger"],
    affiliations: ["steve-rogers", "red-skull", "chester-phillips"],
    artifactsUsed: [],
  },
  {
    key: "hank-pym",
    name: "Hank Pym",
    alias: "The Original Ant-Man",
    description:
      "The physicist who discovered the Pym Particle, worked for S.H.I.E.L.D. alongside Howard Stark, and refused to let anyone weaponise his life's work.",
    powers: ["Size Manipulation", "Quantum Physics", "Genius Intellect"],
    theme: { colorPrimary: "#b91c1c", colorSecondary: "#1e40af" },
    appearances: [
      "ant-man",
      "ant-man-and-the-wasp",
      "avengers-endgame",
      "ant-man-and-the-wasp-quantumania",
    ],
    affiliations: ["howard-stark", "scott-lang"],
    artifactsUsed: [],
  },
  {
    key: "scott-lang",
    name: "Scott Lang",
    alias: "Ant-Man",
    description:
      "Burglar turned size-shifting hero. The Quantum Realm made him five years late to a war, and then handed the Avengers the way to undo it.",
    powers: ["Size Manipulation", "Insect Communication", "Burglary", "Electrical Engineering"],
    theme: { colorPrimary: "#b91c1c", colorSecondary: "#0891b2" },
    appearances: [
      "ant-man",
      "captain-america-civil-war",
      "ant-man-and-the-wasp",
      "avengers-endgame",
      "ant-man-and-the-wasp-quantumania",
    ],
    affiliations: ["hank-pym", "steve-rogers", "sam-wilson", "clint-barton"],
    artifactsUsed: [],
  },
];

export const artifacts = [
  {
    key: "infinity-gauntlet",
    name: "Infinity Gauntlet",
    description:
      "A gilded glove forged to harness all six Infinity Stones, granting its wearer power over reality itself.",
    origin: "Forged by Eitri on Nidavellir",
    powers: ["Reality Warping", "Time Manipulation", "Soul Control"],
    status: "destroyed",
    holders: ["thanos", "tony-stark"],
    appearances: ["avengers-infinity-war", "avengers-endgame"],
  },
  {
    key: "mjolnir",
    name: "Mjolnir",
    description:
      "Thor's enchanted hammer, forged in the heart of a dying star and liftable only by the worthy.",
    origin: "Forged in Nidavellir from Uru metal",
    powers: ["Worthiness Enchantment", "Lightning Summoning", "Flight"],
    status: "destroyed",
    holders: ["thor-odinson", "steve-rogers"],
    appearances: ["the-avengers", "thor-ragnarok", "avengers-endgame"],
  },
  {
    key: "stormbreaker",
    name: "Stormbreaker",
    description:
      "An axe forged to channel the full power of the Bifrost, capable of wounding Thanos.",
    origin: "Forged on Nidavellir during the Infinity War",
    powers: ["Bifrost Summoning", "Energy Channeling", "Flight"],
    status: "active",
    holders: ["thor-odinson"],
    appearances: ["avengers-infinity-war", "avengers-endgame"],
  },
  {
    key: "vibranium-shield",
    name: "Vibranium Shield",
    description:
      "Captain America's near-indestructible shield, capable of absorbing and redirecting kinetic energy.",
    origin: "Wakandan vibranium, forged by Howard Stark",
    powers: ["Kinetic Absorption", "Indestructibility"],
    status: "active",
    holders: ["steve-rogers", "sam-wilson"],
    appearances: ["the-avengers", "captain-america-the-winter-soldier", "avengers-endgame"],
  },
  {
    key: "tesseract",
    name: "Tesseract",
    description:
      "A crystalline cube housing the Space Stone, capable of opening portals across the universe.",
    origin: "Ancient cosmic artifact containing the Space Stone",
    powers: ["Space Manipulation", "Portal Creation", "Energy Source"],
    status: "destroyed",
    holders: ["loki-laufeyson", "thanos"],
    appearances: ["the-avengers", "avengers-infinity-war"],
  },
  {
    key: "eye-of-agamotto",
    name: "Eye of Agamotto",
    description:
      "A mystical relic containing the Time Stone, worn by the Sorcerer Supreme.",
    origin: "Created by Agamotto, the first Sorcerer Supreme",
    powers: ["Time Manipulation", "Temporal Loops"],
    status: "destroyed",
    holders: ["stephen-strange"],
    appearances: ["doctor-strange", "avengers-infinity-war"],
  },
  {
    key: "cloak-of-levitation",
    name: "Cloak of Levitation",
    description:
      "A sentient mystical garment that chooses its wearer and fights alongside them.",
    origin: "Relic of the New York Sanctum",
    powers: ["Flight", "Sentience", "Autonomous Defense"],
    status: "active",
    holders: ["stephen-strange"],
    appearances: ["doctor-strange", "avengers-infinity-war"],
  },
  {
    key: "arc-reactor",
    name: "Arc Reactor",
    description:
      "A miniaturized fusion power source that keeps Tony Stark alive and powers the Iron Man armor.",
    origin: "Built by Tony Stark in a cave in Afghanistan",
    powers: ["Clean Energy Generation", "Armor Power Source"],
    status: "active",
    holders: ["tony-stark"],
    appearances: ["iron-man", "the-avengers", "avengers-endgame"],
  },
  {
    key: "vibranium-suit",
    name: "Black Panther Habit",
    description:
      "A vibranium-weave suit that absorbs kinetic energy and releases it in a concussive blast.",
    origin: "Designed by Shuri in Wakanda",
    powers: ["Kinetic Absorption", "Energy Redistribution", "Nanotech Storage"],
    status: "active",
    holders: ["tchalla"],
    appearances: ["black-panther", "avengers-infinity-war"],
  },
];

export const teams = [
  {
    key: "avengers",
    name: "The Avengers",
    description:
      "Earth's mightiest heroes, assembled by Nick Fury to fight the battles no single hero could win.",
    headquarters: "Avengers Compound, Upstate New York",
    founded: "2012",
    status: "active",
    theme: { colorPrimary: "#c8102e", colorSecondary: "#0a3161" },
    leaders: ["steve-rogers", "tony-stark"],
    members: [
      "tony-stark",
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "natasha-romanoff",
      "clint-barton",
    ],
    appearances: ["the-avengers", "avengers-infinity-war", "avengers-endgame"],
  },
  {
    key: "guardians-of-the-galaxy-team",
    name: "Guardians of the Galaxy",
    description:
      "A band of intergalactic misfits who became the protectors of the cosmos.",
    headquarters: "The Milano",
    founded: "2014",
    status: "active",
    theme: { colorPrimary: "#b45309", colorSecondary: "#7c3aed" },
    leaders: ["peter-quill"],
    members: ["peter-quill", "gamora", "rocket-raccoon", "groot"],
    appearances: ["guardians-of-the-galaxy", "avengers-infinity-war"],
  },
  {
    key: "wakandan-royal-family",
    name: "Wakandan Royal Family",
    description:
      "The ruling line of Wakanda, guardians of the world's only vibranium deposit.",
    headquarters: "Golden City, Wakanda",
    founded: "Ancient",
    status: "active",
    theme: { colorPrimary: "#4c1d95", colorSecondary: "#0f766e" },
    leaders: ["tchalla"],
    members: ["tchalla", "shuri"],
    appearances: ["black-panther", "avengers-infinity-war"],
  },
];

export const battles = [
  {
    key: "battle-of-new-york",
    name: "Battle of New York",
    description:
      "Loki's Chitauri army invades Manhattan through a portal opened by the Tesseract, forcing the newly formed Avengers to fight as a team for the first time.",
    location: "Manhattan, New York City",
    significance: "major",
    outcome:
      "The Avengers close the portal and capture Loki. Tony Stark nearly dies redirecting a nuclear missile through the wormhole.",
    casualties: 74,
    movie: "the-avengers",
    participants: [
      "tony-stark",
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "natasha-romanoff",
      "clint-barton",
      "loki-laufeyson",
    ],
    winner: "steve-rogers",
  },
  {
    key: "highway-ambush",
    name: "Highway Ambush",
    description:
      "The Winter Soldier and HYDRA operatives ambush Steve Rogers, Natasha Romanoff and Sam Wilson on a Washington D.C. overpass.",
    location: "Washington, D.C.",
    significance: "minor",
    outcome:
      "The trio survive but are captured by S.H.I.E.L.D. forces loyal to HYDRA. Steve recognizes Bucky beneath the mask.",
    casualties: 12,
    movie: "captain-america-the-winter-soldier",
    participants: ["steve-rogers", "natasha-romanoff", "sam-wilson", "bucky-barnes"],
    winner: "bucky-barnes",
  },
  {
    key: "battle-of-xandar",
    name: "Battle of Xandar",
    description:
      "The newly formed Guardians confront Ronan the Accuser, who wields the Power Stone above Xandar's capital.",
    location: "Xandar, Nova Empire",
    significance: "major",
    outcome:
      "The Guardians share the Power Stone's burden between them and destroy Ronan, saving Xandar.",
    casualties: 0,
    movie: "guardians-of-the-galaxy",
    participants: ["peter-quill", "gamora", "rocket-raccoon", "groot"],
    winner: "peter-quill",
  },
  {
    key: "duel-at-the-hong-kong-sanctum",
    name: "Duel at the Hong Kong Sanctum",
    description:
      "Doctor Strange reverses time over a destroyed Hong Kong to undo Kaecilius' attack on the Sanctum.",
    location: "Hong Kong",
    significance: "major",
    outcome:
      "Strange rewinds time, restores the Sanctum, and bargains with Dormammu to save Earth.",
    casualties: 0,
    movie: "doctor-strange",
    participants: ["stephen-strange"],
    winner: "stephen-strange",
  },
  {
    key: "contest-of-champions",
    name: "Contest of Champions",
    description:
      "Thor is forced into gladiatorial combat on Sakaar against the Grandmaster's reigning champion - the Hulk.",
    location: "Sakaar",
    significance: "minor",
    outcome:
      "The fight ends in a draw when the Grandmaster intervenes. Thor and Bruce later escape together.",
    casualties: 0,
    movie: "thor-ragnarok",
    participants: ["thor-odinson", "bruce-banner"],
    winner: "bruce-banner",
  },
  {
    key: "challenge-at-warrior-falls",
    name: "Challenge at Warrior Falls",
    description:
      "Erik Killmonger invokes ritual combat to claim the Wakandan throne from T'Challa.",
    location: "Warrior Falls, Wakanda",
    significance: "major",
    outcome: "T'Challa is defeated and thrown from the falls; Killmonger takes the throne.",
    casualties: 3,
    movie: "black-panther",
    participants: ["tchalla"],
    winner: null,
  },
  {
    key: "battle-of-titan",
    name: "Battle of Titan",
    description:
      "Iron Man, Spider-Man, Doctor Strange and the Guardians confront Thanos on his ruined homeworld in a desperate attempt to remove the Gauntlet.",
    location: "Titan",
    significance: "universe-altering",
    outcome:
      "The plan fails when Star-Lord loses control. Thanos takes the Time Stone after Strange surrenders it to preserve the one winning future.",
    casualties: 0,
    movie: "avengers-infinity-war",
    participants: [
      "tony-stark",
      "peter-parker",
      "stephen-strange",
      "peter-quill",
      "gamora",
      "thanos",
    ],
    winner: "thanos",
  },
  {
    key: "battle-of-wakanda",
    name: "Battle of Wakanda",
    description:
      "Thanos' Outriders assault Wakanda's shield in a bid to tear the Mind Stone from Vision's forehead.",
    location: "Golden City, Wakanda",
    significance: "universe-altering",
    outcome:
      "Thanos arrives, takes the Mind Stone, and snaps. Half of all life in the universe turns to dust.",
    casualties: 2000,
    movie: "avengers-infinity-war",
    participants: [
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "natasha-romanoff",
      "tchalla",
      "shuri",
      "bucky-barnes",
      "sam-wilson",
      "rocket-raccoon",
      "groot",
      "thanos",
    ],
    winner: "thanos",
  },
  {
    key: "battle-of-earth",
    name: "Battle of Earth",
    description:
      "Every surviving hero returns through Strange's portals for a final stand against Thanos and his armada at the ruined Avengers Compound.",
    location: "Avengers Compound, Upstate New York",
    significance: "universe-altering",
    outcome:
      "Tony Stark seizes the Infinity Stones and snaps Thanos' army out of existence, sacrificing his own life.",
    casualties: 500,
    movie: "avengers-endgame",
    participants: [
      "tony-stark",
      "steve-rogers",
      "thor-odinson",
      "bruce-banner",
      "clint-barton",
      "peter-parker",
      "stephen-strange",
      "tchalla",
      "peter-quill",
      "rocket-raccoon",
      "groot",
      "thanos",
    ],
    winner: "tony-stark",
  },
];
